# Generated by Django 6.0.6 on 2026-07-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nom du tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Sujet")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "controlled",
                    models.TextField(
                        verbose_name="Ce que je contrôle (actions, pensées)"
                    ),
                ),
                (
                    "uncontrolled",
                    models.TextField(
                        verbose_name="Ce que je ne contrôle pas (résultats externes)"
                    ),
                ),
                (
                    "corrective_action",
                    models.TextField(verbose_name="Action de correction"),
                ),
                (
                    "linked_tasks",
                    models.ManyToManyField(
                        blank=True, to="tasks.task", verbose_name="Tâches liées"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="tasks.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
